pipeline:
  build:
    image: python:2
    pull: true
    push: true
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - flake8 --ignore=E501,F403,F405 jumpbox/
      - nosetests -v --with-coverage --cover-package=jumpbox --cover-inclusive --cover-erase tests
